# -*- mode: python -*-

block_cipher = None


a = Analysis(['..\\src\\main.py',
              '..\\src\\win\\secBootWin.py',
              '..\\src\\ui\\uicore.py',
              '..\\src\\gen\\gencore.py',
              '..\\src\\run\\runcore.py',
              '..\\src\\mem\\memcore.py',
              '..\\src\\win\\bootDeviceWin_FlexspiNor.py',
              '..\\src\\win\\bootDeviceWin_FlexspiNand.py',
              '..\\src\\win\\bootDeviceWin_SemcNor.py',
              '..\\src\\win\\bootDeviceWin_SemcNand.py',
              '..\\src\\win\\bootDeviceWin_UsdhcSd.py',
              '..\\src\\win\\bootDeviceWin_UsdhcMmc.py',
              '..\\src\\win\\bootDeviceWin_RecoverySpiNor.py',
              '..\\src\\win\\bootDeviceWin_DCD.py',
              '..\\src\\win\\advSettingsWin_Cert.py',
              '..\\src\\win\\advSettingsWin_FixedOtpmkKey.py',
              '..\\src\\win\\advSettingsWin_FlexibleUserKeys_Bee.py',
              '..\\src\\win\\advSettingsWin_FlexibleUserKeys_Otfad.py',
              '..\\src\\ui\\uivar.py',
              '..\\src\\ui\\uidef.py',
              '..\\src\\ui\\ui_cfg_flexspinor.py',
              '..\\src\\ui\\ui_cfg_flexspinand.py',
              '..\\src\\ui\\ui_cfg_semcnor.py',
              '..\\src\\ui\\ui_cfg_semcnand.py',
              '..\\src\\ui\\ui_cfg_usdhcsd.py',
              '..\\src\\ui\\ui_cfg_usdhcmmc.py',
              '..\\src\\ui\\ui_cfg_recoveryspinor.py',
              '..\\src\\ui\\ui_cfg_dcd.py',
              '..\\src\\ui\\ui_settings_cert.py',
              '..\\src\\ui\\ui_settings_fixed_otpmk_key.py',
              '..\\src\\ui\\ui_settings_flexible_user_keys_bee.py',
              '..\\src\\ui\\ui_settings_flexible_user_keys_otfad.py',
              '..\\src\\boot\\bltest.py',
              '..\\src\\boot\\commands.py',
              '..\\src\\boot\\memoryrange.py',
              '..\\src\\boot\\peripherals.py',
              '..\\src\\boot\\peripheralspeed.py',
              '..\\src\\boot\\properties.py',
              '..\\src\\boot\\status.py',
              '..\\src\\boot\\target.py',
              '..\\src\\targets\\MIMXRT595\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT685\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT1011\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT1021\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT1052\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT1062\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT1064\\bltargetconfig.py',
              '..\\src\\targets\\MIMXRT1176\\bltargetconfig.py',
              '..\\src\\utils\\elf.py',
              '..\\src\\utils\\filetools.py',
              '..\\src\\utils\\misc.py'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='NXP-MCUBootUtility',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='NXP-MCUBootUtility',
               icon='..\\img\\NXP-MCUBootUtility.ico')
